create TABLE locations
(
    LOCATION_ID NUMBER,
    STREET_ADDRESS VARCHAR2(25),
    POSTAL_CODE VARCHAR2(12),
    CITY VARCHAR(30)
    STATE_PROVINCE VARCHAR2(12)
    COUNTRY_ID CHAR(2)    
    )
    select * from locations
insert into locations(LOCATION_ID,STREET_ADDRESS,POSTAL_CODE,CITY,STATE_PROVINCE,COUNTRY_ID)
values(26122022,);

STRUCTURE OF HR DATA BASE