create TABLE employees
(
    EMPLOYEE_ID NUMBER,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(25),
    EMAIL VARCHAR2(25)
    PHONE_NUMBER VARCHAR2(20)
    HIRE_DATE DATE
    JOB_ID VARCHAR2(10)
    SALARY NUMBER
    COMMISSION_PCT NUMBER
    MANAGER_ID NUMBER
    DEPARTMENT_ID NUMBER
    )
    select * from employees
insert into employees(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)
values(26122022,);

STRUCTURE OF HR DATA BASE